# Generated by Django 5.1.4 on 2024-12-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_brand_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Accessories', 'Accessories'), ('Shoe Wear', 'Shoe Wear'), ('Stoles', 'Stoles')], default='uncategorized', max_length=50),
        ),
    ]
